name: Deploy Core Server

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/core-server/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "Dockerfile"
      - ".github/workflows/deploy-server.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/core-server:latest

      - name: Dokploy Deployment Trigger
        uses: benbristow/dokploy-deploy-action@0.2.2
        with:
          api_token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          application_id: ${{ vars.DOKPLOY_APPLICATION_ID }}
          dokploy_url: ${{ vars.DOKPLOY_URL }}
          service_type: application
